### ISSUE TITLE
objective-C version

### ISSUE THREAD

**Issue by CavalcanteLeo** [lojals/JOEmojiableBtn#1]
is there an objective-c version?

I mean a real version written in objc-c, not to include using bridge

**Comment by lojals** [comment]
No, is not. But is a good idea, you're free to contribute developing an ObjC version.

**Comment by Eke** [comment]
Hello @lojals,

i started writing objective-c version. if you are interested, can add to repo

**Comment by CavalcanteLeo** [comment]
@Eke do you need any help?

**Comment by Eke** [comment]
@CavalcanteLeo Thank you, at this moment no, in few hours i will make repo public and post link here. than any help will be perfect

**Comment by Eke** [comment]
@CavalcanteLeo [Here it is](https://github.com/Eke/EMEmojiableBtn)

@lojals I added swift version backlink to this repo, but if you want more info to be added about original implementation, contact me and i will add.

**Comment by CavalcanteLeo** [comment]
inserted both on [awesome-ios](https://github.com/CavalcanteLeo/awesome-ios/blob/db9ad146d2d4dc329627b377de9650f38442282b/README.md#button)

**Comment by lojals** [comment]
@Eke, I added you in the Readme file giving credits for the objc implementation and link to the EMEmojiableBtn, you can do the same in your repo if you want. 
📱🍕

**Comment by Eke** [comment]
@lojals added too
