### ISSUE TITLE
selectedOption never get called

### ISSUE THREAD

**Issue by satyamub** [lojals/JOEmojiableBtn#4]
Hi,
I am trying your example however, I see that the selectedOption here never gets called so I don't get chance to check if user select something. Overtime, its showing "User cancelled".

**Comment by lojals** [comment]
@satyamub what device are you using? could be more descriptive?

**Comment by satyamub** [comment]
I am testing this on Simulator.. is there an issue with simulator...

**Comment by lojals** [comment]
- I just clone the repo, and did the whole process and it works,
- I'm using xcode 7.3.
- There's a [video](https://youtu.be/Y1_gHsyJ0nM) I just capture.

**Comment by aliasnoa** [comment]
I am having this problem and can't seem to fix it.  I an't select any of them, it just says "user cancelled"

**Comment by aliasnoa** [comment]
Oh I see, you have to long tap to get them to pop up, then release, then long tap to select one again.  Is it supposed to be like that?  I want to make it so that I can release the initial long-tap on one of them to select, or release and then single tap one to select it.

**Comment by lojals** [comment]
@aliasnoa  is that the way that facebook works, one tap = like, long tap open the Reactions, then you can scroll to select your reaction. Maybe in the next version I can put a selection in each reaction like a button.

**Comment by aliasnoa** [comment]
but what I'm saying is, you have to long tap to bring up the reactions, then release and long tap again to pick one

**Comment by lojals** [comment]
@aliasnoa indeed, in this version works in that way.

**Comment by aliasnoa** [comment]
I'm just saying if you could do it all in one long press instead of 2, it would be just like Facebook.  I'm trying to figure out how to do it but there's a lot of stuff I'm not familiar with

**Comment by lojals** [comment]
For sure I'll do it in the next version, but right now I don't have time. The thing is, that the control of the **touchesBegan** method, work in the first button but then I create another overlay to track the tap position, the control from the long tap is not transferred to the overlay. This will still open while I implement it.

**Comment by aliasnoa** [comment]
Okay.  Well i'll let you know if I figure it out before then but I doubt I will..would be really cool though because it's so close right now to being perfect...it's very impressive.

**Comment by aliasnoa** [comment]
I wonder if it would be possible to do the hold to pull them up, then select one on single click.  I'm going to try that...that wouldn't be too bad.

**Comment by lojals** [comment]
Go ahead my friend. Just let me know if you make some progress! 🤓

**Comment by satyamub** [comment]
@lojals @aliasnoa What ever I do .. I can't select one...

**Comment by jakezeal** [comment]
Fixed this!
